its:
    app:
        jwtCookieName: its
        jwtExpirationMs: 3600000
        jwtSecret: ======================ITS=VN===========================
server:
    port: 8080
    servlet:
        context-path: /api/v1
spring:
    application:
        name: its-management
    datasource:
        username: admin
        password: its-admin
        url: jdbc:postgresql://172.31.224.1:5432/its_vn_management



    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true
springdoc:
    api-docs:
        path: /swagger-doc/v3/api-docs
    swagger-ui:
        operationsSorter: method
